include: "rules/common.smk"


## Target rule -----------------------------------------------


rule all:
    input:
        "results/all.snps.pass.barcoded.tsv",


## Workflow rules --------------------------------------------


include: "rules/reference.smk"
include: "rules/mapping.smk"
include: "rules/calling.smk"
include: "rules/barcoding.smk"
