# Adjust these parameters based on your setup

files:
  samples: config/samples.tsv # Path to the samples tab-delimited file
  barcodes: workflow/barcodes/barcodes.tsv # Barcodes

# Email required by NCBI
email: user@mail.com

# Threads for BWA-MEM
BWA:
  threads: 2

GATK:
  markdup:
    memory: 1024 # Memory for Picard MarkDuplicates in mb
  hapcall:
    memory: 1024 # Memory for GATK HaplotypeCaller in mb
    threads: 2 # Threads for GATK HaplotypeCaller in mb
  gendb:
    memory: 10240 # Memory for GATK GenomicsDBImport in mb
  genotype:
    memory: 10240 # Memory for GATK GenotypeGVCFs in mb
  filter:
    memory: 10240 # Memory for GATK VariantFiltration in mb
  select:
    memory: 1024 # Memory for GATK SelectVariants in mb
