# You can adjust the parameters according to your setup

files:
  samples: config/samples.tsv # The path to the tab-separated values file containing the paths to the analysed samples
  barcodes: resources/barcodes.tsv # A tab-separated values file with barcoding SNPs
  dummy: resources/dummy.g.vcf.gz # A dummy vcf for lineage 4 barcoding
  levels: resources/levels.tsv # File with levels barcodes
  intervals: resources/intervals.bed # BED file with intervals of interest

NCBI:
  H37Rv-reference-genome:
    - NC_000962.3 # Mycobacterium tuberculosis H37Rv RefSeq accession number

BWA:
  threads: 8 # Threads for BWA-MEM

GATK:
  markdup:
    memory: 1024 # Memory for Picard MarkDuplicates in mb
  hapcall:
    memory: 10240 # Memory for GATK HaplotypeCaller in mb
    threads: 8 # Threads for GATK HaplotypeCaller in mb
  gendb:
    memory: 10240 # Memory for GATK GenomicsDBImport in mb
  genotype:
    memory: 10240 # Memory for GATK GenotypeGVCFs in mb
  filter:
    memory: 10240 # Memory for GATK VariantFiltration in mb
  select:
    memory: 1024 # Memory for GATK SelectVariants in mb
